<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple Page with Header Menu</title>
    <link rel="stylesheet" href="mal.css" />
</head>
<body>

    <?php
    include('include.php');
    ?>


    <!-- Navigation menu -->
    <nav>
        <ul>
            <li><a href="#home">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#services">Services</a></li>
            <li><a href="#contact">Contact</a></li>
        </ul>
    </nav>

    <!-- Main content -->
    <div class="content">
        <h2>Main Content Area</h2>
        <p>This is where your main content will go.</p>
        <p>You can add text, images, and other HTML elements here.</p>
        <p>&nbsp;</p><!-- &nbsp; i HTML lager whitespace tilsvarende ett tegn -->

        <section id="about" style="background-color: #f4f4f4;">
            <h2>About Us</h2>
            <p>This is the About section. You can add any content related to your site here.</p>
            <p><img src="https://si360opengov.blob.core.windows.net/b3ae595c-6b77-4c84-82bb-657e98b4bfe7/UIA.jpg" width="90%"></img></p>
        </section>

        <section id="services" style="background-color: #e2e2e2;">
            <h2>Our Services</h2>
            <p>This is the Services section where you can describe the services you offer.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin interdum a enim id ultricies. Suspendisse vulputate fringilla neque, eget fringilla arcu porta ut. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed in dapibus turpis. Integer posuere, ipsum at venenatis congue, enim lectus porta lacus, et imperdiet velit diam vitae diam. Phasellus vel elementum lectus, vitae lacinia magna. Proin sed lobortis nulla. Proin tempus convallis arcu at commodo. Morbi nec nisi euismod, posuere purus sit amet, blandit ante. Curabitur volutpat varius fringilla.</p>
        </section>

        <section id="contact" style="background-color: #d1d1d1;">
            <h2>Contact Us</h2>
            <p>This is the Contact section with contact information.</p>
        </section>


    </div>

    <!-- Footer section -->
    <footer>
        <p>This file is generated by ChatGPT.</p>
    </footer>

</body>
</html>
